### ISSUE TITLE
OnenMCT attempting to connect to couch DB

### ISSUE THREAD

**Issue by at-ms** [scottbell/openmct-quickstart#3]
HI 

I have been trying to run the openmct-quickstart over the last day or two (for the first time) and hitting an issue that openmct is attempting to connect to couchdb but never does.

<img width="323" alt="open mct connection attempt" src="https://github.com/scottbell/openmct-quickstart/assets/133143171/3485b5c3-8f45-4df2-b74a-a2f2219d7748">
<img width="1187" alt="couchdb tables" src="https://github.com/scottbell/openmct-quickstart/assets/133143171/53f67f58-5a73-4042-b401-5154268d7349">

Win 11
Docker Desktop: Docker Engine v24.0.7

**Comment by scottbell** [comment]
@at-ms Interesting. Can you please share the status of your docker containers? It looks like you were able to get CouchDB up? Is there anything in the Javascript console log?

**Comment by at-ms** [comment]
Apologies for not feeding back sooner, looked like hardcoded IP's in the apache config were the problem and worked after resolving this

docker exec openmct-quickstart-apache-1 sed -i 's/192\.168\.22\.3/127.0.0.1/g' /usr/local/apache2/htdocs/openmct/openmct-quickstart.js

**Comment by scottbell** [comment]
> Apologies for not feeding back sooner, looked like hardcoded IP's in the apache config were the problem and worked after resolving this
> 
> docker exec openmct-quickstart-apache-1 sed -i 's/192.168.22.3/127.0.0.1/g' /usr/local/apache2/htdocs/openmct/openmct-quickstart.js

Ah yes, we noticed this too. This [should be fixed now](https://github.com/scottbell/openmct-quickstart/commit/5daafb50dea9fecd1ecd7c005e6079e3375331ea). Please verify this works for you, and we can close the ticket.

**Comment by scottbell** [comment]
Closing for the time being - let me know if you run into it again!
